### ISSUE TITLE
Trying to run a simulation results in error when reading ddck-files

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys#107]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/67690903/160091586-262dd22e-fd5d-4f59-9573-9af6a9024887.png)

**Comment by martin-neugebauer** [comment]
@zuckerruebe FYI

**Comment by martin-neugebauer** [comment]
This folder contains the file from which the simulation was launched:

[run.zip](https://github.com/SPF-OST/pytrnsys/files/8349105/run.zip)

**Comment by zuckerruebe** [comment]
This should be fixed.
