### ISSUE TITLE
Using type 14 leads to unit nr. replacement issues

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys#113]
@ToniCal18 is encountering issues with the unit nr. replacement when trying to use type 14. He will provide the ddck-file in question.

**Comment by ToniCal18** [comment]
I am including the DDCk file and also the dck file.
[ezyzip.zip](https://github.com/SPF-OST/pytrnsys/files/8426168/ezyzip.zip)
