### ISSUE TITLE
Remove default for output temperature and ignore when not using GUI

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys#134]
See https://github.com/SPF-OST/pytrnsys/issues/133 for more background.

We shall not allow a default any more for output temperature variables. I.e. the ddcks need to be adjusted from

```
@temp(Out, TCollOut) = [42, 7]
```

to

```
@temp(Out) = [42, 7]
```

In non-GUI mode `pytrnsy` should just "ignore" the line (i.e. skip it when compiling the dck file).

**Comment by martin-neugebauer** [comment]
Done.
