### ISSUE TITLE
Processing crashes while reading csv file (nRows must be integer >= 0)

### ISSUE THREAD

**Issue by ahobeost** [SPF-OST/pytrnsys#182]
As a User, I would like the post-processing to be more forgiving.
An issue with one file can stop the post-processing of an entire parameter study.

https://github.com/SPF-OST/pytrnsys/blob/master/pytrnsys/psim/simulationLoader.py
![image](https://github.com/SPF-OST/pytrnsys/assets/122869062/4805487b-0b6f-439f-89be-113f6f0dc101)

An example file in question belongs to a "failed" simulation.
Instead of a year, it only simulated one month:
![image](https://github.com/SPF-OST/pytrnsys/assets/122869062/e65df9b4-a222-4c39-96cf-6857d76fe081)

The files of a "successful" simulation are much longer:
![image](https://github.com/SPF-OST/pytrnsys/assets/122869062/67b27136-a3ed-4163-996f-a0174a043cee)

Thus, it would make sense to only process "successful" simulations.

**Comment by ahobeost** [comment]
Raising the error in a try, except block seems to stop the one process without crashing all processes.
This seems strange to me, as it is the same error.

**Comment by zuckerruebe** [comment]
That's fixed in the newest version.
