### ISSUE TITLE
command ETRACE is not being recognized

### ISSUE THREAD

**Issue by djokru** [SPF-OST/pytrnsys#197]
![image](https://github.com/SPF-OST/pytrnsys/assets/162145289/d7efc9b0-d8a8-40f3-864c-0cc47aed107b)
when manually adding the ETRACE command to the .dck file and running it with TRNexe it works fine

**Comment by ahobeost** [comment]
Here, we can add TRACE, ETRACE, NOLINK, LINK to the parser.
