### ISSUE TITLE
Cases with more than 11 cpu

### ISSUE THREAD

**Issue by tpean** [SPF-OST/pytrnsys#46]
In the file: pytrnsys/rsim/runParallel.py
There are only the cases up to 11 CPUs. Having 16 CPUs on my PC I had some errors. Adding the following cases:
`    elif cpu == 12:
        return 800
    elif cpu == 13:
        return 1000
    elif cpu == 14:
        return 2000
    elif cpu == 15:
        return 4000
    elif cpu == 16:
        return 8000`
solved the problem.

**Comment by zuckerruebe** [comment]
Thanks for the input, @tpean, I will have a look at that.
