### ISSUE TITLE
string plotHourly not working

### ISSUE THREAD

**Issue by danielcarbonell** [SPF-OST/pytrnsys#69]
It seems that it does not read the first variable.
For string plotHourly "TGHXout" I get 
raise KeyError(key) from err
KeyError: 'T'

so it takes the first letter only as string.

**Comment by martin-neugebauer** [comment]
@zuckerruebe Can you have a look at this?

**Comment by zuckerruebe** [comment]
@danielcarbonell `plotHourly` is of type `stringArray`: `stringArray plotHourly "TGHXout"` should work.
