### ISSUE TITLE
Color data points in comfortHourly according to season

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys#88]
![image](https://user-images.githubusercontent.com/67690903/144460208-86693a6d-7aa2-407c-b5ac-7e5374cbfb43.png)
As a user I would like the data points to be colored according to the month they occurred:
Dec-Feb
Mar-May
Jun-Aug
Sep-Nov

**Comment by DanielPhilippen** [comment]
Martin, after you left today, we discussed also the boundaries/comfort zones: for me they are quite odd. 17 °C won't be accepted in winter as people will feel cold. Maybe it's something physiological: 17 °C are okay for the nose if the air is humid? So, the zones should be modifiable as well :)

**Comment by martin-neugebauer** [comment]
I agree that they are odd, but they were simply taken from the respective publication. The boundaries are adjustable in the python source code, but I really wouldn't make them controllable from the config-file, since this will just lead to long command lines. I guess we don't want to change them from plot to plot, but just find correct ones once and keep them.

**Comment by ToniCal18** [comment]
I agree 100% on that Martin. The plots come from publications and we should keep them as they are. To present our simulation results in terms of comfort, maybe we could simply use the other plot (according to ISO7730) already available that seems to be more plausible.
Anyway as soon as Daniel clarifies with CVUT definition/norms in terms of comfort for Czech Republic maybe we could simply implement another plot according to Czech norms if necessary.

**Comment by martin-neugebauer** [comment]
Yes, additional norms are no problem. 👍
